---
title: " TIL&TEL 21.03.08~21.03.14  "
date: "2021-03-14T01:23:45.678Z"
template: "post"
draft: false
slug: "/posts/TIL&TEL_21-03-14/"
category: "TIL&TEL"
tags:
- "TIL"
- "TEL"


description: " 21.03.08~21.03.14 배운것, 씨름한것들 "
---

## TIL( Today I Learned)

### 21-03-08 월

- 업무
  - Vm 젠킨스이전
  - django cg api permission 변경
    - dictionary['key']는 에러를 유발할 가능성이 높다. .get()을 권장하자.

### 21-03-09 화

- 업무
  - bert 코드 보기
    - app 쪼개기
      - create_app( ) 팩토리 생성 패턴 만들기

### 21-03-10 수

- 업무
  - 플라스크 쪼개기

### 21-03-11 목

- nlp_process
- html
- api 수정

### 21-03-12 금

- 업무
  - ElasticSearch 문서 인덱싱 추가
  - 변경된 내역 dmc api 배포하기


## TEL (Trial and Error Log)

### 21-03-08

- ERROR: GCP VM ssh 접속 안됨

  - SITUATION: ssh, gcp console 접속이 안됨
  - REASON: vm에러
  - SOLUTION:
    - VM 재설정(재시작)

- ERROR: tar : Cannot open: File exists

  - SITUATION: tar로 압축해제중
  - REASON: others have no write permission
    - 권한 문제이다 
    - 권한 문제이다
    - 권한 문제이다
    - 기존에 있는 tar 파일 수정 권한이 없다.
  - SOLUTION:
    - 권한 있는 계정으로 진행한다.

- ERROR: tar : 압축이 안풀린다

  - SITUATION: Publish Over SSH 동작에서 문제가 발생한다
  - REASON: 명령어 실행 위치로 이동을 안했다.
  - SOLUTION:
    - cd <target>

- ERROR: django api server 500

  - SITUATION: django 실행중
  - REASON: request.headers['key']로 값 가져오는중
  - SOLUTION:
    - .get() 으로 변경한다.

- ERROR: This site can’t provide a secure connection - ERR_SSL_PROTOCOL_ERROR

  - SITUATION: 브라우저에서 아예 접속을 못함

  - REASON:

     

    - Incorrect computer data and time settings
    - **Mismatched SSL certificate name with the domain name**
    - Untrusted, outdated or unauthorized SSL certificate
    - Antivirus or firewall protection
    - Webpage containing some insecure data
    - Browser problem

  - SOLUTION:

    - DNS 네임 get

- ERROR: GIT remote: Public key authentication failed. // fatal: Could not read from remote repository.

  - SITUATION: 깃 업데이트
  - REASON: 다른 프로젝트였다.
  - SOLUTION:
    - git remote -v 로 연결된 브런치 확인한다

### 21-03-10

- ERROR:No module named 'tensorflow_core.keras'
  - SITUATION: flask runserver 동작을 못함
  - REASON: tf 공식 에러
  - SOLUTION:
    - tf 2.2 이상 올라가야함
- ERROR: create_app() takes 0 positional arguments but 2 were given
  - SITUATION: flask initiating
  - REASON: 명령어를 잘못 침
  - SOLUTION:
    - uwsgi ~~ "app:func()" <= uwsgi ~ app:func
- ERROR: Bert Serving TypeError: 'NoneType' object is not iterable
  - SITUATION: bert serving initiating
  - REASON: ckpt number 잘못 입력
  - SOLUTION:
    - ckpt 0 한개 뺌

### 21-03-11

- ERROR: Specifying limit and offset in Django QuerySet wont work
  - SITUATION: django queryset[offset:limit] test
  - REASON:
    - 
      You were printing (or, at least, trying to print) the repr() of the queryset. To avoid people accidentally trying to retrieve and print a million results, we (well, I) changed that to only retrieve and print the first 20 results and print "remainder truncated" if there were more. This is achieved by limiting the query to 21 results (if there are 21 results there are more than 20, so we print the "truncated" message). That only happens in the **repr**() -- i.e. it's only for diagnostic printing. No normal user code has this limit included automatically, so you happily create a queryset that iterates over a million results.
  - SOLUTION:
    - not error, intended result by maker 
- ERROR:html script default radio selected
  - SITUATION: default 동작이 필요하다.
  - REASON: 
  - SOLUTION:
    - <input ~~~ checked>
      - 이렇게 하면 불만 들어와 있는다.
    - 라디오버튼이 동작을 할때
    - <body onload= function() > 
      - 이렇게 하면 라디오 선택function이 동작한다.
- ERROR: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame
  - SITUATION: dataframe 편집하는상황
  - REASON: 원본 보존을 위해 변조를 막는다. 
  - SOLUTION:
    - .copy() method를 사용, 새로운 df instance를 만든다.

### 21-03-12

- ERROR: ElasticSearch RequestError(400, 'resource_already_exists_exception'
  - SITUATION: elasticsearch indexing
  - REASON: ElasticSearch 기존 동작 중인 녀석이 있다.
  - SOLUTION: 기존 동작 off
- ERROR:pip3 bad interpreter: No such file or directory
  - SITUATION: python3 이동후 call
  - REASON: 다른 파이썬을 불러온다
    - [참고](https://stackoverflow.com/questions/51373063/pip3-bad-interpreter-no-such-file-or-directory)
  - SOLUTION:
    - pip shebang 변경 
- ERROR:StartupException: java.lang.IllegalStateException: failed to obtain node locks,
  - SITUATION: elasticsearch 재부팅중
  - REASON: 이미 가동중인 녀석이 있다.
  - SOLUTION:
    - netstat -nlp | grep 9200으로 잡아서 처리한다.